version: "3.9" 
services:
  table_detection:
    build: table_detection/
    ports:
      - "${TABLE_DETECTION_PORT}:80"
    volumes:
      - ./table_detection:/code
    restart: always
  table_recognition:
    build: table_recognition/
    ports:
      - "${TABLE_RECOGNITION_PORT}:80"
    volumes:
      - ./table_recognition:/code
    restart: always
